#ifndef MQL5_PRICE_ACTION_EVENT_IDS_MQH
#define MQL5_PRICE_ACTION_EVENT_IDS_MQH
// SPR4-011 Price Action Event Registry — infrastructure identifiers only
const string EVT_PRICEACTION_INIT = "PRICEACTION_INIT";
const string EVT_PRICEACTION_UPDATE = "PRICEACTION_UPDATE";
const string EVT_PRICEACTION_READY = "PRICEACTION_READY";
const string EVT_PRICEACTION_SHUTDOWN = "PRICEACTION_SHUTDOWN";
const string EVT_CANDLE_BULLISH = "CANDLE_BULLISH";
const string EVT_CANDLE_BEARISH = "CANDLE_BEARISH";
const string EVT_CANDLE_DOJI = "CANDLE_DOJI";
const string EVT_ENGULFING_DETECTED = "ENGULFING_DETECTED";
const string EVT_ENGULFING_CONFIRMED = "ENGULFING_CONFIRMED";
const string EVT_ENGULFING_REJECTED = "ENGULFING_REJECTED";
const string EVT_PINBAR_DETECTED = "PINBAR_DETECTED";
const string EVT_PINBAR_CONFIRMED = "PINBAR_CONFIRMED";
const string EVT_PINBAR_REJECTED = "PINBAR_REJECTED";
const string EVT_INSIDEBAR_DETECTED = "INSIDEBAR_DETECTED";
const string EVT_INSIDEBAR_CONFIRMED = "INSIDEBAR_CONFIRMED";
const string EVT_INSIDEBAR_REJECTED = "INSIDEBAR_REJECTED";
const string EVT_OUTSIDEBAR_DETECTED = "OUTSIDEBAR_DETECTED";
const string EVT_OUTSIDEBAR_CONFIRMED = "OUTSIDEBAR_CONFIRMED";
const string EVT_OUTSIDEBAR_REJECTED = "OUTSIDEBAR_REJECTED";
const string EVT_FIBONACCI_UPDATED = "FIBONACCI_UPDATED";
const string EVT_FIBONACCI_READY = "FIBONACCI_READY";
const string EVT_RETRACEMENT_FOUND = "RETRACEMENT_FOUND";
const string EVT_RETRACEMENT_CONFIRMED = "RETRACEMENT_CONFIRMED";
const string EVT_CONFLUENCE_UPDATED = "CONFLUENCE_UPDATED";
const string EVT_CONFLUENCE_READY = "CONFLUENCE_READY";
#endif // MQL5_PRICE_ACTION_EVENT_IDS_MQH
