#pragma once
// SPR3-010 Structure Event Registry — infrastructure identifiers only
const string EVT_SWING_FOUND = "SWING_FOUND";
const string EVT_SWING_UPDATED = "SWING_UPDATED";
const string EVT_SWING_CONFIRMED = "SWING_CONFIRMED";
const string EVT_SWING_REJECTED = "SWING_REJECTED";
const string EVT_SWING_STORED = "SWING_STORED";
const string EVT_SWING_RESTORED = "SWING_RESTORED";
const string EVT_BOS_DETECTED = "BOS_DETECTED";
const string EVT_BOS_CONFIRMED = "BOS_CONFIRMED";
const string EVT_BOS_REJECTED = "BOS_REJECTED";
const string EVT_CHOCH_DETECTED = "CHOCH_DETECTED";
const string EVT_CHOCH_CONFIRMED = "CHOCH_CONFIRMED";
const string EVT_CHOCH_REJECTED = "CHOCH_REJECTED";
const string EVT_TREND_UPDATED = "TREND_UPDATED";
const string EVT_TREND_CHANGED = "TREND_CHANGED";
const string EVT_TREND_RESET = "TREND_RESET";
const string EVT_STRUCTURE_INIT = "STRUCTURE_INIT";
const string EVT_STRUCTURE_UPDATE = "STRUCTURE_UPDATE";
const string EVT_STRUCTURE_SHUTDOWN = "STRUCTURE_SHUTDOWN";
